export const COLLEGES = [
    "Lakshmi Narain College of Technology (LNCT) Bhopal",
    "Rajiv Gandhi Proudyogiki Vishwavidyalaya (R.G.P.V) Bhopal",
    "Oriental College of Technology Bhopal(OCT)",
    "Technocrats Institute of Technology (TIT) Bhopal",
    "Sagar Institute of Research & Technology (SIRT) Bhopal",
    "People's University Bhopal",
    "Maulana Azad National Institute of Technology(MNIT)",
    "IIIT Bhopal",
    "Barkatullah University Bhopal",
    "AIMS Bhopal",
    "RKDF University Bhopal",
    "Madhyanchal Professional University Bhopal",
    "University of Delhi — Delhi",
    "University of Mumbai — Mumbai",
    "Savitribai Phule Pune University — Pune",
    "University of Calcutta — Kolkata",
    "University of Madras — Chennai",
    "Bangalore University — Bengaluru",
    "Osmania University — Hyderabad",
    "Chaudhary Charan Singh University — Meerut",
    "Dr. Bhimrao Ambedkar University — Agra",
    "University of Rajasthan — Jaipur",
    "Magadh University — Bodh Gaya",
    "Patna University — Patna",
    "Lucknow University — Lucknow",
    "Banaras Hindu University — Varanasi",
    "University of Allahabad — Prayagraj",
    "Ranchi University — Ranchi",
    "Veer Bahadur Singh Purvanchal University — Jaunpur",
    "Deen Dayal Upadhyaya Gorakhpur University — Gorakhpur",
    "Jai Prakash University — Chhapra",
    "Tilka Manjhi Bhagalpur University — Bhagalpur",
    "Mahatma Gandhi Kashi Vidyapith — Varanasi",
    "Utkal University — Bhubaneswar",
    "Berhampur University — Berhampur",
    "North Maharashtra University — Jalgaon",
    "Shivaji University — Kolhapur",
    "Kakatiya University — Warangal",
    "Andhra University — Visakhapatnam",
    "Sri Venkateswara University — Tirupati",
    "University of Mysore — Mysuru",
    "Gulbarga University — Kalaburagi",
    "Dr. Ram Manohar Lohia Avadh University — Ayodhya",
    "Bundelkhand University — Jhansi",
    "Chhatrapati Shahu Ji Maharaj University — Kanpur",
    "Sampurnanand Sanskrit University — Varanasi",
    "Mahatma Jyotiba Phule Rohilkhand University — Bareilly",
    "Siddharth University — Kapilvastu (Siddharthnagar)",
    "Raja Mahendra Pratap Singh State University — Aligarh",
    "Shakumbhari Devi University — Saharanpur",
    "Gautam Buddha University — Greater Noida",
    "Maharaja Suheldev State University — Azamgarh",
    "Maa Shakumbhari University — Saharanpur",
];

export const CITIES = [
    "Delhi NCR",
    "Mumbai",
    "Kolkata",
    "Chennai",
    "Bengaluru",
    "Hyderabad",
    "Ahmedabad",
    "Pune",
    "Surat",
    "Jaipur",
    "Lucknow",
    "Kanpur",
    "Nagpur",
    "Indore",
    "Thane",
    "Bhopal",
    "Visakhapatnam",
    "Patna",
    "Vadodara",
    "Ghaziabad",
    "Ludhiana",
    "Agra",
    "Nashik",
    "Faridabad",
    "Meerut",
    "Rajkot",
    "Varanasi",
    "Srinagar",
    "Aurangabad",
    "Dhanbad",
    "Amritsar",
    "Navi Mumbai",
    "Allahabad (Prayagraj)",
    "Ranchi",
    "Howrah",
    "Coimbatore",
    "Jabalpur",
    "Gwalior",
    "Vijayawada",
    "Jodhpur",
    "Madurai",
    "Raipur",
    "Kota",
    "Chandigarh",
    "Guwahati",
    "Noida",
    "Greater Noida",
];
